### ISSUE TITLE
Power text are not clickable

### ISSUE THREAD

**Issue by bibirico** [seagiants/proto-zero#3]
One can't click on the power case text. To activate a power, one needs to click around the text on the case.

**Comment by romaintailhurat** [comment]
Solved with [this commit](https://github.com/seagiants/proto-zero/commit/55531d1fcfca4a0f06773fabe94db33749c954db).

I used a [wrapper function](https://github.com/seagiants/proto-zero/blob/master/src/components/PowerCase.js#L23) for that which is used for both <rect/> and <text/> elements onClick methods.
